-- 코드를 작성해주세요
 SELECT
COUNT(*) AS FISH_COUNT
FROM
FISH_INFO a JOIN FISH_NAME_INFO b
ON a.FISH_TYPE = b.FISH_TYPE
WHERE
a.FISH_TYPE = (SELECT FISH_TYPE FROM FISH_NAME_INFO WHERE FISH_NAME = 'BASS')
OR a.FISH_TYPE = (SELECT FISH_TYPE FROM FISH_NAME_INFO WHERE FISH_NAME = 'SNAPPER')
