SELECT I.ID, MAXTABLE.FISH_NAME, MAXTABLE.LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
JOIN 
        (
        SELECT N.FISH_NAME, MAX(I.LENGTH) AS LENGTH
        FROM FISH_INFO I
        LEFT JOIN FISH_NAME_INFO N
        ON I.FISH_TYPE = N.FISH_TYPE
        GROUP BY N.FISH_NAME
        ) AS MAXTABLE
ON N.FISH_NAME = MAXTABLE.FISH_NAME AND 
    I.LENGTH = MAXTABLE.LENGTH
ORDER BY I.ID;
