SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
       (M_LENGTH - SIZE_OF_COLONY )AS YEAR_DEV,
       ID
FROM ECOLI_DATA D
JOIN (
    SELECT  YEAR(DIFFERENTIATION_DATE) AS YEAR, 
            MAX(SIZE_OF_COLONY) AS M_LENGTH
    FROM    ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS M
ON YEAR(D.DIFFERENTIATION_DATE)= M.YEAR
ORDER BY YEAR, YEAR_DEV;
-- 날짜로 정렬하는 경우, 날짜 형식 유지해야함.
