SELECT 
    ID,
    CASE 
        WHEN RANKING <= (SELECT COUNT(*) FROM ECOLI_DATA) * 0.25 THEN 'CRITICAL'
        WHEN RANKING <= (SELECT COUNT(*) FROM ECOLI_DATA) * 0.50 THEN 'HIGH'
        WHEN RANKING <= (SELECT COUNT(*) FROM ECOLI_DATA) * 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID,
           RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANKING
    FROM ECOLI_DATA
) AS ranked_data
ORDER BY ID;
