SELECT E.ID
    FROM ECOLI_DATA E
    LEFT JOIN ECOLI_DATA E2 ON E.PARENT_ID = E2.ID
    LEFT JOIN ECOLI_DATA E3 ON E2.PARENT_ID = E3.ID
WHERE E2.PARENT_ID IS NOT NULL AND E3.PARENT_ID IS NULL
ORDER BY E.ID;
