-- 코드를 입력하세요
SELECT
e.TITLE,e.BOARD_ID,d.REPLY_ID,e.WRITER_ID,e.CONTENTS,
DATE_FORMAT(e.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE
FROM 
USED_GOODS_BOARD  e
JOIN USED_GOODS_REPLY d
ON e.BOARD_ID = d.BOARD_ID
WHERE e.CREATED_DATE like '2022-10%'
ORDER BY e.CREATED_DATE ,e.TITLE
