SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE*O.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER O 
JOIN FOOD_PRODUCT P
ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE SUBSTR(PRODUCE_DATE,1,7)='2022-05'
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY SUM(P.PRICE*O.AMOUNT) DESC, P.PRODUCT_ID
