-- 조인 없이
SELECT FLAVOR
FROM(
    SELECT *
    FROM FIRST_HALF
    UNION ALL
    SELECT *
    FROM JULY
    ORDER BY FLAVOR) AS DATATABLE
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3;

-- 조인 사용
SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR) AS J
ON F.FLAVOR = J.FLAVOR
ORDER BY F.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3;
