SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE*(1-P.DISCOUNT_RATE*0.01)*30,0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단','SUV')
    AND P.DURATION_TYPE = '30일 이상'
    AND C.CAR_ID NOT IN (SELECT CAR_ID --NOT IN 사용 
         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
         WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-12-01')
    AND C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)*0.01 >= 500000 
    AND C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)*0.01 < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC
