SELECT i.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM REST_INFO i 
JOIN 
(SELECT REST_ID ,ROUND(AVG(REVIEW_SCORE), 2) as SCORE FROM REST_REVIEW GROUP BY REST_ID) r
ON i.REST_ID = r.REST_ID 
WHERE ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;
