SELECT D.HISTORY_ID,
       CASE 
            WHEN D.PLAN_ID IS NULL THEN ROUND(D.DIFF*D.DAILY_FEE)
            ELSE ROUND(D.DIFF*D.DAILY_FEE*(1-P.DISCOUNT_RATE*0.01)) END AS FEE
FROM 
    (
    SELECT H.HISTORY_ID, C.CAR_ID,C.CAR_TYPE,C.DAILY_FEE,
           CASE
                WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 >= 90 THEN 12
                WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 >= 30 THEN 11
                WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 >= 7 THEN 10
                ELSE NULL END AS PLAN_ID,
        DATEDIFF(H.END_DATE,H.START_DATE)+1 AS DIFF
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
    ) AS D
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON D.PLAN_ID = P.PLAN_ID
ORDER BY FEE DESC, D.HISTORY_ID DESC;
